### ISSUE TITLE
Question 1 wording

### ISSUE THREAD

**Issue by caltry** [caltry/CSC-reviews#7]
From Chris Sherry:

Question 1: I don't like the word delimiters. I can't think of a better one at the moment ('encapsulating punctuation'?) but when I think of delimiters it is more of commas and whitespace.

**Comment by masterpi314** [comment]
The consensus seems to be that brackets or braces is the best name for the group of them but that it doesn't work in American English because those generally refer to the more specific forms.  Proposed resolution is moving the whole school to England, or indoctrinating everyone by watching the entirety of Doctor Who, The IT Crowd, and Red Dwarf.

http://english.stackexchange.com/questions/14252/what-is-the-common-name-for-brackets-braces-and-parentheses

**Comment by caltry** [comment]
Fixed in 675bde3e6c209b9098186e58fec8e2708d40aa9f
